### PR TITLE
Elm locust notebook

### PR DESCRIPTION
**Pull request by emackev**
Adding documentation to `locust-approximate-pipeline.ipynb`

### CODE REVIEW

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
See comments on reviewNB.

**Comment by emackev** [comment]
<p>yup</p>

---

 <a href='https://app.reviewnb.com/BasisResearch/collab-creatures/pull/68/discussion/#comment-1994560039'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by emackev** [comment]
<p>Added some explanation. Please verify that it's accurate, including the part about plotting (<code>For ease of plotting, the communicate trace is only shown a a random subset of locations.</code> -- consider adding what percentage is plotted?  )</p>

---

 <a href='https://app.reviewnb.com/BasisResearch/collab-creatures/pull/68/discussion/#comment-1994560070'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rfl-urbaniak** [comment]
<p>So the sub-sampling there takes place prior to predictor derivation, added an explanation earlier, and removed the one about plotting.</p>

---

 <a href='https://app.reviewnb.com/BasisResearch/collab-creatures/pull/68/discussion/#comment-1994560070'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by rfl-urbaniak — APPROVED** [review]

**Pull request merged**
