### PR TITLE
Import fish data for velocity calculations

### PR DESCRIPTION
**Pull request by PalkaPuri**

### CODE REVIEW

**Comment by PalkaPuri** [comment]
@rfl-urbaniak I reduced the data folder by having only a single experiment of each age, as discussed. Other files can be accessed via drive link mentioned in README.

**Review by rfl-urbaniak — CHANGES_REQUESTED** [review]
If I understand correctly, this really just throws csvs and brief data info into a folder, which is a great start. But is a sense, there is no test as to whether these data sets import nicely and can be converted into an object as intended.

I would recommend adding for now a a folder in `docs/experimental/fish` in which your experimental notebooks can live, and creating one notebook there that (1) defines an import pipeline for those datasets, (2) performs imports for all of them ensuring this happens without failures, and (3) ends with basic visualizations and animations as designed to ensure that these do not yield incorrect results when applied to imported data.

**Comment by PalkaPuri** [comment]
Hi, yes, these are just the data files. 
I ran checks on whether the files are able to be imported & converted to data objects on a separate branch (pp-experimental, in docs/velocity/fish-data-test.ipynb). While the objects can be created without issues, derivation of scores yields errors because of the nan values when fish go missing. That is yet to be solved, and is going to be a separate PR to either chop up the movies or update the score functions. Thought i would import the data for now, in the spirit of keeping PRs small.

**Comment by rfl-urbaniak** [comment]
I think creating objects and animations still matters as a basic sanity
test for data formatting and our animation functions. I agree that
derivation and whatnot is a separate issue, but I still would include this
basic test in this PR with the idea that changes and modifications should
come with a proof that they make sense and some test.

**Comment by PalkaPuri** [comment]
Alright. Will add a NB demonstrating these tests later in the week and get back to you!

**Comment by rfl-urbaniak** [comment]
Thanks!

**Comment by PalkaPuri** [comment]
I needed the new rescale_to_grid() function to correctly import and display the fish data. So I combined this change with the rescale_to_grid PR (#85). The nb validating the data import is included (docs/experimental/fish/fish_import_checks.ipynb). So I'm closing this PR now!

**Pull request closed without merging**
