### PR TITLE
Refactoring velocity predictors

### PR DESCRIPTION
**Pull request by PalkaPuri**
Updated formulation of Vicsek predictors to remove vector averaging of velocity magnitude. The velocity magnitude is now sampled from a gaussian centered at the velocity of previous time step. Previously used `_generic_velocity_predictor` with a mechanism-specific transformation of interaction partner velocities did not allow for this change in the vicsek predictor. So I have now removed it, and I directly wrote two generate functions for pairwiseCopying and vicsek.

### CODE REVIEW

**Comment by rfl-urbaniak** [comment]
We updated staging-collab-2, please make sure you pull origin, resolve conflicts and pass the tests.

**Comment by PalkaPuri** [comment]
I updated `velocity_predictors.ipynb` to have test both pairwiseCopying and vicsek predictors, removed `vicsek_predictor.ipynb`. Also pruned the notebook to only use the non-underscored (exposed) generate functions. Found a bug in `animate_predictors` that did not allow plotting positions of a selected set of foragers. Fixed that in this PR as well.

**Comment by PalkaPuri** [comment]
I deleted `compute_velocity.ipynb` which tests `_add_velocity` function since (1) we want to avoid importing underscored functions (2) `_add_velocity` is implicitly tested when `generate_pairwiseCopying_predictor` and `generate_vicsek_predictor` are called in `velocity_predictors.ipynb`

**Comment by PalkaPuri** [comment]
Hi @rfl-urbaniak, @dimkab - this one is ready to review as well. The following changes were made 
1. Updated the formulation of vicsek predictors so that speed is not averaged, only direction. (averaging speed frequently leads to v=0 when neighbors point in different directions. this is not consistent with biological animal movements)
2. The previous formulation in terms of a "generic_velocity_predictor" did not allow for the change in 1. So I refactored the code to have separate generate function for vicsek and pairwiseCopying predictors.
3. I added a test notebook `velocity_predictors.ipynb` to collab_tests folder that replaces the suspended tests
4. There was a bug in the animation that did not allow choosing specific forager indices to be animated. Fixed that as well.
5. Removed import of underscored velocity functions in the toolkit init file

Note that this PR already contains the changes made in pp-add-velocity-bug (#118) so I would merge that first.

**Review by rfl-urbaniak — APPROVED** [review]
LGTM

**Pull request merged**
