### PR TITLE
add_velocity_to_foragers

### PR DESCRIPTION
**Pull request by rfl-urbaniak**
This tiny PR just adds and tests a function that adds velocities to foragers data. Note, this does not derive any predictors yes, just expands the forager data with two columns.

### CODE REVIEW

**Comment by emackev** [comment]
It may make sense to smooth the velocity in time, because it's currently almost all discrete (e.g. 0, 1, -1 pixels/frame). What smoothing makes sense will depend on the dataset, but something like average velocity over a 0.5 second smoothing window may be good for the birds. What do you think?

**Comment by rfl-urbaniak** [comment]
created a new issue to handle later. Merging for now.

**Review by emackev — COMMENTED** [review]
OK to merge, we can construct different version of velocity in the future.

**Review by emackev — APPROVED** [review]
https://docs.google.com/document/d/1ou4jFwQa23Okg8OFD9-s3NLWeM6pxeaPNUxa__ijzLg/edit

**Pull request merged**
